FROM homebrew/brew:latest

COPY packages/brew/core.Brewfile /tmp/core.Brewfile
COPY packages/brew/zsh.Brewfile /tmp/zsh.Brewfile

RUN brew bundle --file=/tmp/core.Brewfile && \
    brew bundle --file=/tmp/zsh.Brewfile

CMD ["echo", "Brewfile packages validated"]